# Generated by Django 3.2.9 on 2021-12-07 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='trade_description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='wanted_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
