# Generated by Django 3.2.9 on 2021-12-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211207_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='author_picture_link',
            field=models.TextField(null=True),
        ),
    ]
