# Generated by Django 3.2.9 on 2021-12-13 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20211208_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
