# Generated by Django 3.2.9 on 2021-12-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_post_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar_image',
        ),
    ]
