# Generated by Django 3.2.9 on 2021-12-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_post_avatar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='trade_description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='wanted_description',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
