# Generated by Django 3.2.9 on 2022-03-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20220314_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='trade_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='trade_image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='trade_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='trade_image4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='trade_image5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
