# Generated by Django 3.2.9 on 2022-03-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_postimages_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostImages',
        ),
    ]
