# Generated by Django 3.2.9 on 2021-12-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='lng',
            field=models.IntegerField(null=True),
        ),
    ]
